apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openobserve-data
  namespace: cloud
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: cloud
  labels:
    app: openobserve
spec:
  clusterIP: None
  selector:
    app: openobserve
  ports:
  - name: http
    port: 5080
    targetPort: 5080
  - port: 5081
    name: grpc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openobserve-v1
  namespace: cloud
  labels:
    app: openobserve
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
      version: v1
  template:
    metadata:
      labels:
        app: openobserve
        version: v1
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
    spec:
      serviceAccount: cloud
      containers:
        - name: openobserve
          image: swr.cn-north-1.myhuaweicloud.com/yunzai/openobserve:v1
          env:
             - name: RUST_LOG
               value: error
             - name: ZO_META_STORE
               value: postgres
             - name: ZO_META_POSTGRES_DSN
               value: "postgres://yunzai:mars.yunzai@master.ds.svc.cluster.local:5432/mars"
             - name: ZO_OAUTH2_ALLOWED_ROLES
               value: ROLE_ADMIN
             - name: ZO_BASE_URI
               value: /openobserve
             - name: ZO_WEB_URL
               value: ${BASE_URL}/openobserve
             - name: ZO_OAUTH2_USERINFO_URL
               value: http://auth:3000/auth/user
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 5080
              path: /openobserve/
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 5080
              path: /openobserve/
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            limits:
              cpu: 4096m
              memory: 12Gi
            requests:
              cpu: 256m
              memory: 50Mi
          ports:
          - containerPort: 5080
            name: http
          - containerPort: 5081
            name: grpc
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openobserve-data
  
